# Auto-report action script

name: Auto-report action

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '10 15 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install tesseract-ocr 
    - name: Run report script
      env:
        STUID: ${{ secrets.Stuid }}
        PASSWORD: ${{ secrets.Password }}
      run: |
        python runme.py "$STUID" "$PASSWORD"
